### ISSUE TITLE
FP

### ISSUE THREAD

**Issue by Geksanit** [NZMinusDev/jq-range-slider#10]
У нас на проектах пишут в функциональной парадигме (на сколько это возможно). У этого есть куча плюсов, какие могу рассказать, но интернет расскажет лучше) 
т.е. не должно быть никаких мутаций, `delete`, и мутрущих методов, таких как `sort`. [есть пункт в наших стандартах
](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#8.3)![image](https://user-images.githubusercontent.com/31949379/149916228-28b8ffdb-494c-4e86-811f-03180cd253b3.png)
К примеру тут можно обойтись методом reduce.
А почему метод `_fixIntervalsOption` нигде не используется?

**Comment by NZMinusDev** [comment]
> А почему метод `_fixIntervalsOption` нигде не используется? 
![image](https://user-images.githubusercontent.com/70576143/150084513-529720bb-1aa4-4886-919a-32edddd935dc.png)

**Comment by NZMinusDev** [comment]
мутации уберу в ближайшее время
