### ISSUE TITLE
Абстрактные классы

### ISSUE THREAD

**Issue by Geksanit** [NZMinusDev/jq-range-slider#11]
Какова причина существования всех этих абстрактных классов - `RangeSliderAbstractPresentationModel`, `AbstractPresentationModel` и т.д.?

**Comment by NZMinusDev** [comment]
`AbstractPresentationModel` - это общий архитектурный шаблон презентационной модели, позволяет пере использовать модель паттерна MVP;
`RangeSliderAbstractPresentationModel` - это контракт для презентационной модели в слайдере, позволяет подменять модели если возникнет такая необходимость;
`RangeSliderMainPresentationModel` - конкретная реализация презентационной модели слайдера.
