### ISSUE TITLE
Недоработки слайдера

### ISSUE THREAD

**Issue by vendmm** [NZMinusDev/jq-range-slider#2]
На шкалу слайдера нужно добавить промежуточные значения, при клике на которые ползунок должен перемещаться на позицию этого значения

**Comment by vendmm** [comment]
![2021-10-29-08-34-46](https://user-images.githubusercontent.com/90188872/139386518-dfc8eabe-1760-403f-bb0e-c5c875028aea.png)

Мне кажется на панели, которая показывает текущее значение бегунков, лучше отображать максимум два числа после запятой

**Comment by NZMinusDev** [comment]
> На шкалу слайдера нужно добавить промежуточные значения, при клике на которые ползунок должен перемещаться на позицию этого значения

Имеется ввиду что клики должны срабатывать по заполнителю? - думаю это не должно так работать, ибо это чисто графическое дополнение(да и попадать по ним сложно) + можно нажимать шкалу самого слайдера

![76c1gV9Jne](https://user-images.githubusercontent.com/70576143/139388068-ad429bd9-2cf8-40f9-b05e-0d79cce2bfbc.gif)

**Comment by vendmm** [comment]
Не заметила сразу, что добавление промежуточных значений происходит в отдельном инпуте. Мне кажется лучше сделать отображение определенного кол-ва значений по умолчанию.

Не совсем понятно зачем есть возможность менять кол-во заполнителей на шкале. При значении 100 это сказывается на скорости работы слайдера, возможно здесь так же стоит ограничиться неким дефолтным значением

**Comment by NZMinusDev** [comment]
> Не заметила сразу, что добавление промежуточных значений происходит в отдельном инпуте. Мне кажется лучше сделать отображение определенного кол-ва значений по умолчанию.

для всех опций есть значения по умолчанию, описаны в *README*: для линейки это - отобразить значения для каждого интервала и использовать заполнитель с плотностью 1

> Не совсем понятно зачем есть возможность менять кол-во заполнителей на шкале. При значении 100 это сказывается на скорости работы слайдера, возможно здесь так же стоит ограничиться неким дефолтным значением

добавлю ограничитель на максимально допустимое значение
