### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by vendmm** [NZMinusDev/jq-range-slider#5]
Зачем нужно создавать 2 файла IModel  в папке models и экспортировать один в другой
![2021-11-05-13-46-04](https://user-images.githubusercontent.com/90188872/140499006-000fa660-0e53-4f38-88d6-49ea9d3271d8.png)

![2021-11-05-13-47-42](https://user-images.githubusercontent.com/90188872/140499212-d209456f-b885-48b6-bbd9-ec723ff5d90b.png)

почему бы сразу не экспортировать IRangeSliderModel в configurable-slider-demo/IModel

**Comment by NZMinusDev** [comment]
> Зачем нужно создавать 2 файла IModel в папке models и экспортировать один в другой ![2021-11-05-13-46-04]

Заменил названия `IModel` на соответствующие расположению файла: `SliderModel` и `ConfigurableSliderDemoModel`.

> почему бы сразу не экспортировать IRangeSliderModel в configurable-slider-demo/IModel

Потому что компонент `ConfigurableSliderDemo` использует `RangeSlider`(плагин) не напрямую, а через обертку - компонент `Slider`. 'Сторонние' же компоненты предпочитаю использовать оборачивая их чтобы в дальнейшем можно было модифицировать компонент, а не лезть в код плагинов.

**Comment by vendmm** [comment]
Сейчас твоя вьюха содержит в себе логику для валидации данных, поступающих от модели. Она не должна выполнять эту работу. Данные, которые поступают в модель, нужно валидировать в модели и передавать их вьюхе уже в готовом виде, а вью должна заниматься только их отображением.

**Comment by NZMinusDev** [comment]
На данный момент *view* выполняет валидацию связанную только с отображением, а именно: выводит только `start.length` количество данных, ограничивает максимальное и минимальное значение границами `interval.max - interval.min`-`padding`, сортирует порядок для удобства внутренней реализации - *view* выводит данные( `value`) в том виде, в каком может/удобно вывести, основываясь на опциях отображения.

Думаю, выносить опции отображения в модель - не самая хорошая практика, если нет дополнительных условий реализации(например необходимости параллельной работы программистов над одним компонентом) т.к. тогда будет происходить смешение презентационной логики и логики получения данных предметной области(бизнес логика же чаще всего выносится на сервер и в этом проекте её вообще нет - модель тонкая) - или же под каждую subview придется делать свою Presentation Model(она же Application Model) в виде подмодели с состоянием отображения, что для презентационного уровня избыточно(увеличивается зацепление при снижении единства из-за размазывания презентационной логики(становится 2 модуля вместо 1, причем они жестко связаны)) - это уже не MVP Passive view. Еще одним преимуществом текущей реализации является то, что *view* является самодостаточной и представляет из себя полноценный модуль визуализации(инкапсулирует логику отображения, настройки и способна работать самостоятельно), что больше подходит концепции plugin-а - о *модели* же в данном случае лучше думать как о фасаде для получения бизнес-данных с сервера, что пользователям плагинов обычно и нужно задавать самостоятельно.

В самом задании говорится, что модель не должна отвечать за логику отображения(хотя тут понять можно двояко).
> У вашего приложения должны быть четко разделенные слои приложения:
>   1. Нужно сделать отдельный слой управления данными (Model), который будет содержать бизнес-логику приложения и не производить никаких расчетов, которые нужны для отображения.
>   2. Отдельный слой для управления отображением (View) — здесь нельзя проводить никаких расчетов, относящихся к бизнес-логике. Слой должен содержать логику, связанную с отображением (например, для изменения положения ползунка слайдера на экране), а также реагировать на взаимодействие пользователя с приложением.  Каждый компонент слайдера (бегунки, шкала и т. д.) должен быть представлен отдельным классом. Благодаря такой декомпозиции View, функционал будет четко разделен между subViews, а вы научитесь решать проблемы взаимодействия в рамках многоуровневой структуры.
> ...
>    4. На выходе должно получиться подобие MVP-архитектуры с Passive View.

Как я понял, либо тут ошибка в задании, либо имеет место недопонимание: твоё замечание состоит в том, что в реализации используется не dumb view. Текущие опции *view* и работа с ними может трактоваться как "логика, связанная с отображением" и Passive view !== dumb view.

**Comment by vendmm** [comment]
К логике связанной с отображением можно отнести расчет нового положения бегунка, информацию о размере слайдера и т.д. Сейчас же помимо этого вью занимается корректировкой мин и макс значений, расчетом кол-ва шагов, возможных в пределах заданных значений, проверяет не выходит ли значение бегунка за пределы мин и макс. Все это необходимо отнести к бизнес-логике приложения и выполнение этих расчетов должно происходить в модели.
