### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by AkhmadBabaev** [NZMinusDev/jq-range-slider#7]
Компоненты А который импортирует компонент B, должен импортировать ещё и стили компонента B, для большей самостоятельности компонента. Например компонент radio-group импортирует heading, form-field в разметку, но может и импортировать стили данных компонентов в своей стилей файл.

**Comment by NZMinusDev** [comment]
Теперь стили компонентов и стили + скрипты подкомпонентов подключаются через ts файлы явным образом.
